version: '3.7'
services:

  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      #- MINIO_NOTIFY_AMQP_ENABLE=true
      #- MINIO_NOTIFY_AMQP_URL=amqp://root:root@rabbitmq:5672

#
## Settings and configurations that are common for all containers
#x-minio-common: &minio-common
#  image: quay.io/minio/minio:RELEASE.2022-01-28T02-28-16Z
#  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
#  expose:
#    - "9000"
#    - "9001"
#  environment:
#    MINIO_ROOT_USER: minio
#    MINIO_ROOT_PASSWORD: minio123
#    MINIO_NOTIFY_AMQP_ENABLE: 'true'
#    MINIO_NOTIFY_AMQP_URL: amqp://root:root@rabbitmq:5672
#    MINIO_NOTIFY_AMQP_EXCHANGE: messageExchange
#    MINIO_NOTIFY_AMQP_ROUTINGKEY: messageRoutingKey
#  healthcheck:
#    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
#    interval: 30s
#    timeout: 20s
#    retries: 3
#
## starts 4 docker containers running minio server instances.
## using nginx reverse proxy, load balancing, you can access
## it through port 9000.
#services:
#  minio1:
#    <<: *minio-common
#    hostname: minio1
#    volumes:
#      - data1-1:/data1
#      - data1-2:/data2
#
#  minio2:
#    <<: *minio-common
#    hostname: minio2
#    volumes:
#      - data2-1:/data1
#      - data2-2:/data2
#
#  minio3:
#    <<: *minio-common
#    hostname: minio3
#    volumes:
#      - data3-1:/data1
#      - data3-2:/data2
#
#  minio4:
#    <<: *minio-common
#    hostname: minio4
#    volumes:
#      - data4-1:/data1
#      - data4-2:/data2
#
#  nginx:
#    image: nginx:1.19.2-alpine
#    hostname: nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    depends_on:
#      - minio1
#      - minio2
#      - minio3
#      - minio4
#
#  rabbitmq:
#    container_name: rabbitmq
#    image: rabbitmq:3.8-management-alpine
#    restart: "no"
#    environment:
#      - RABBITMQ_DEFAULT_USER=root
#      - RABBITMQ_DEFAULT_PASS=root
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#
### By default this config uses default local driver,
### For custom volumes replace with volume driver configuration.
#volumes:
#  data1-1:
#  data1-2:
#  data2-1:
#  data2-2:
#  data3-1:
#  data3-2:
#  data4-1:
#  data4-2: